# Primeros pasos 

## Strings 

In [1]:
# string1
string1 = "Esto es un string"

"Esto es un string"

In [2]:
# string2
string2 = """Esto es otro
string"""

"Esto es otro\nstring"

In [3]:
print(string2)

Esto es otro
string

In [4]:
# string3
string3 = """En estos strings se pueden poner " sin error"""

"En estos strings se pueden poner \" sin error"

In [5]:
print(string3)

En estos strings se pueden poner " sin error

#### Asignación de variables 

Las variables seasignan con el operador `=`. Por defecto, __en la consola o el notebook__, la asignación se imprime por pantalla si es la última entrada de la celda

In [6]:
a = 27
b = 52

52

Esto no ocurre en los scripts. Para evitar que se imprimam por pantalla, basta con utilizar `;`

In [7]:
a = 55;

### Concatenación 

En julia los string se concatenan con `*`

In [8]:
string1 * string1

"Esto es un stringEsto es un string"

> While * may seem like a surprising choice to users of languages that provide + for string concatenation, this use of * has precedent in mathematics, particularly in abstract algebra.
In mathematics, + usually denotes a commutative operation, where the order of the operands does not matter. An example of this is matrix addition, where A + B == B + A for any matrices A and B that have the same shape. In contrast, * typically denotes a noncommutative operation, where the order of the operands does matter. An example of this is matrix multiplication, where in general A * B != B * A. As with matrix multiplication, string concatenation is noncommutative: greet * whom != whom * greet. As such, * is a more natural choice for an infix string concatenation operator, consistent with common mathematical use.

https://pkg.julialang.org/docs/julia/THl1k/1.1.1/manual/strings.html#man-concatenation-1

En consecuancia con lo anterior, la repetición del string se realiza con `^`

In [9]:
string1 ^5

"Esto es un stringEsto es un stringEsto es un stringEsto es un stringEsto es un string"

### Interpolación 

In [10]:
nombre = "Alex"
print("Hola $(nombre), encantado de conocerte")

Hola Alex, encantado de conocerte

## Tipos numéricos

### Operaciones

In [11]:
# Operaciones
2 * 4 - (7 + 1) / 3^2  

7.111111111111111

In [12]:
# División es real
7 / 3

2.3333333333333335

In [13]:
# Números complejos
1im

0 + 1im

In [14]:
# División entera ¿¿??
7 // 3

7//3

In [15]:
# División entera
div(7, 3)

2

#### Pidiendo ayuda

Veamos qué hace la función div:

In [16]:
?div

search: div divrem DivideError splitdrive code_native @code_native



```
div(x, y)
÷(x, y)
```

The quotient from Euclidean division. Computes `x/y`, truncated to an integer.

# Examples

```jldoctest
julia> 9 ÷ 4
2

julia> -5 ÷ 3
-1
```


In [17]:
7 ÷ 3

2

#### Usando caracteres especiales 

Todo está codificado en utf8, por lo que podemos usar (y su uso está extendido) diferentes símbolos:

In [18]:
α = 0.1
β = 0.6

🚀 = "rocket"

"rocket"

#### Obteniendo el tipo 

In [19]:
# entonces, ¿qué es `7//3`?
typeof(7//3)

Rational{Int64}

#### Métodos para un tipo 

In [20]:
# ¿qué puedo hacer con él?
methodswith(Rational)

[1] rem(x::Rational, y::Rational) in Base at rational.jl:252
[2] *(x::Rational, y::Rational) in Base at rational.jl:259
[3] +(x::Rational, y::Rational) in Base at rational.jl:252
[4] -(x::Rational) in Base at rational.jl:238
[5] -(x::Rational, y::Rational) in Base at rational.jl:252
[6] /(x::Rational, y::Complex{#s72} where #s72<:Union{Integer, Rational}) in Base at rational.jl:264
[7] /(x::Rational, y::Rational) in Base at rational.jl:263
[8] //(x::Rational, y::Integer) in Base at rational.jl:46
[9] //(x::Integer, y::Rational) in Base at rational.jl:50
[10] //(x::Rational, y::Rational) in Base at rational.jl:54
[11] <(x::Rational, y::Rational) in Base at rational.jl:270
[12] <(x::Rational, y::Integer) in Base at rational.jl:278
[13] <(x::Integer, y::Rational) in Base at rational.jl:279
[14] <(x::Rational, y::AbstractFloat) in Base at rational.jl:296
[15] <(x::AbstractFloat, y::Rational) in Base at rational.jl:296
[16] <=(x::Rational, y::Rational) in Base at rational.jl:272
[17] <=(x::Rational, y::Integer) in Base at rational.jl:280
[18] <=(x::Integer, y::Rational) in Base at rational.jl:281
[19] <=(x::Rational, y::AbstractFloat) in Base at rational.jl:296
[20] <=(x::AbstractFloat, y::Rational) in Base at rational.jl:296
[21] <=(x::AbstractIrrational, y::Rational) in Base at irrationals.jl:119
[22] <=(x::Rational, y::AbstractIrrational) in Base at irrationals.jl:120
[23] ==(z::Complex, x::Rational) in Base at rational.jl:345
[24] ==(x::Rational, z::Complex) in Base at rational.jl:346
[25] ==(x::Rational, y::Rational) in Base at rational.jl:269
[26] ==(x::Rational, y::Integer) in Base at rational.jl:276
[27] ==(x::Integer, y::Rational) in Base at rational.jl:277
[28] ==(x::AbstractFloat, q::Rational) in Base at rational.jl:284
[29] ==(q::Rational, x::AbstractFloat) in Base at rational.jl:291
[30] ^(::Irrational{:ℯ}, x::Rational) in Base.MathConstants at mathconstants.jl:91
[31] ^(z::Complex{T}, p::Rational) where T<:Real in Base at rational.jl:438
[32] ^(x::Rational, n::Integer) in Base at rational.jl:433
[33] ^(x::T, y::Rational) where T<:AbstractFloat in Base at rational.jl:437
[34] ^(x::Number, y::Rational) in Base at rational.jl:436
[35] abs(x::Rational) in Base at rational.jl:231
[36] big(q::Rational) in Base at sysimg.jl:407
[37] ceil(::Type{T}, x::Rational) where T>:Missing in Base at missing.jl:118
[38] ceil(::Type{T}, x::Rational) where T in Base at rational.jl:368
[39] cld(x::Rational, y::Integer) in Base at rational.jl:351
[40] cld(x::Integer, y::Rational) in Base at rational.jl:355
[41] cld(x::Rational, y::Rational) in Base at rational.jl:359
[42] cmp(x::Rational, y::AbstractFloat) in Base at rational.jl:296
[43] cmp(x::AbstractFloat, y::Rational) in Base at rational.jl:296
[44] copysign(x::Rational, y::Rational) in Base at rational.jl:229
[45] copysign(x::Rational, ::Unsigned) in Base at sysimg.jl:400
[46] copysign(x::Rational, y::Real) in Base at rational.jl:228
[47] denominator(x::Rational) in Base at rational.jl:224
[48] div(x::Rational, y::Integer) in Base at rational.jl:351
[49] div(x::Integer, y::Rational) in Base at rational.jl:355
[50] div(x::Rational, y::Rational) in Base at rational.jl:359
[51] fld(x::Rational, y::Integer) in Base at rational.jl:351
[52] fld(x::Integer, y::Rational) in Base at rational.jl:355
[53] fld(x::Rational, y::Rational) in Base at rational.jl:359
[54] flipsign(x::Rational, ::Unsigned) in Base at sysimg.jl:399
[55] floor(::Type{T}, x::Rational) where T>:Missing in Base at missing.jl:118
[56] floor(::Type{T}, x::Rational) where T in Base at rational.jl:367
[57] fma(x::Rational, y::Rational, z::Rational) in Base at rational.jl:267
[58] inv(x::Rational) in Base at rational.jl:265
[59] isinteger(x::Rational) in Base at rational.jl:236
[60] isone(x::Rational) in Base at rational.jl:446
[61] iszero(x::Rational) in Base at rational.jl:445
[62] mod(x::Rational, y::Rational) in Base at rational.jl:252
[63] numerator(x::Rational) in Base at rational.jl:207
[64] round(::Type{T}, x::Rational) w

In [21]:
# resto de la división
rem(7, 3)

1

In [22]:
# y también
7 % 3

1

### Punto flotante 

In [23]:
# preserve
println("1 / Inf -> $(1/Inf)")
println("1 / 0 -> $(1/0)")
println("-5 / 0 -> $(-5 / 0 )")
println("0.00001 / 0 -> $(0.00001 / 0)")
println("0 / 0 -> $(0 / 0)")
println("500 + Inf -> $(500 + Inf)")
println("500 - Inf -> $(500 - Inf)")
println("Inf + Inf-> $(Inf + Inf)")
println("Inf / Inf -> $(Inf/Inf)")
println("0 / Inf -> $(0/Inf)")
println("Inf / 0 -> $(Inf/0)")

1 / Inf -> 0.0
1 / 0 -> Inf
-5 / 0 -> -Inf
0.00001 / 0 -> Inf
0 / 0 -> NaN
500 + Inf -> Inf
500 - Inf -> -Inf
Inf + Inf-> Inf
Inf / Inf -> NaN
0 / Inf -> 0.0
Inf / 0 -> Inf


In [24]:
# distancia número más cercano
eps(1.0)

2.220446049250313e-16

In [25]:
# eps de un tipo
eps(Float64)

2.220446049250313e-16

In [26]:
eps(Float32)

1.1920929f-7

In [27]:
# Flotante anterior
prevfloat(Inf)

1.7976931348623157e308

In [28]:
# Cambio de tipo Int -> Float
Float64(1)

1.0

In [29]:
# Float -> Int
Int(1.0)

1

In [30]:
# También podemos usar convert
convert(Int64, 1.0)

1

In [31]:
# Truncar ??
Int64(1.1)

InexactError: InexactError: Int64(1.1)

In [32]:
# Truncar
trunc(-1.1)

-1.0

In [33]:
# Truncar a entero
trunc(Int64, -1.1)

-1

In [34]:
# Redondear
round(1.1)

1.0

### Comparaciones

In [35]:
0.1 + 0.2 + 0.3 > 0.4

true

In [36]:
0.1 + 0.2 + 0.3 == 0.6

false

In [37]:
1//10 + 2//10 + 3//10  == 6//10

true

In [38]:
Float64(1//10 + 2//10 + 3//10)

0.6

In [39]:
0.6 == Float64(6//10)

true

## Arrays 

In [40]:
# Creando un array de números aleatorios 3x3
arr = rand(3, 3)

3×3 Array{Float64,2}:
 0.790302  0.207395  0.816905
 0.320043  0.345702  0.23298 
 0.849122  0.548789  0.629812

In [41]:
# Tipo del array
eltype(arr)

Float64

In [42]:
# Longitud
length(arr)

9

In [43]:
# Tamaño
size(arr)

(3, 3)

In [44]:
# Número de dimensiones
ndims(arr)

2

### Indexación 

In [45]:
arr[1, 1]

0.7903015394069359

In [46]:
arr[1, :]

3-element Array{Float64,1}:
 0.7903015394069359 
 0.20739488903069292
 0.816905010229052  

In [47]:
arr[end, end]

0.6298122281078329

In [48]:
arr .> 0.5

3×3 BitArray{2}:
  true  false   true
 false  false  false
  true   true   true

In [49]:
arr[arr .> 0.5]

5-element Array{Float64,1}:
 0.7903015394069359
 0.8491218482762515
 0.548788509002154 
 0.816905010229052 
 0.6298122281078329

### Otras inicializaciones típicas 

In [50]:
zeros(10)

10-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [51]:
ones(10)

10-element Array{Float64,1}:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0

In [52]:
x = range(0, 10, step=0.5)

0.0:0.5:10.0

In [53]:
x = range(0, 10, length=21)

0.0:0.5:10.0

In [54]:
x = collect(x)

21-element Array{Float64,1}:
  0.0
  0.5
  1.0
  1.5
  2.0
  2.5
  3.0
  3.5
  4.0
  4.5
  5.0
  5.5
  6.0
  6.5
  7.0
  7.5
  8.0
  8.5
  9.0
  9.5
 10.0

In [55]:
x = collect(0:0.5:10)

21-element Array{Float64,1}:
  0.0
  0.5
  1.0
  1.5
  2.0
  2.5
  3.0
  3.5
  4.0
  4.5
  5.0
  5.5
  6.0
  6.5
  7.0
  7.5
  8.0
  8.5
  9.0
  9.5
 10.0

In [56]:
# Comprehension
[sin(x) for x in 0:0.1:2pi]

63-element Array{Float64,1}:
  0.0                
  0.09983341664682815
  0.19866933079506122
  0.2955202066613396 
  0.3894183423086505 
  0.479425538604203  
  0.5646424733950355 
  0.6442176872376911 
  0.7173560908995228 
  0.7833269096274834 
  0.8414709848078965 
  0.8912073600614354 
  0.9320390859672264 
  ⋮                  
 -0.9258146823277321 
 -0.8834546557201531 
 -0.8322674422239008 
 -0.7727644875559871 
 -0.7055403255703919 
 -0.6312666378723208 
 -0.5506855425976376 
 -0.4646021794137566 
 -0.373876664830236  
 -0.27941549819892586
 -0.18216250427209502
 -0.0830894028174964 

In [57]:
# Generator expression
(sin(x) for x in 0:0.1:2pi)

Base.Generator{StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}},typeof(sin)}(sin, 0.0:0.1:6.2)

### Operaciones 

In [58]:
arr1 = [1 2 3;
            4 5 6]

2×3 Array{Int64,2}:
 1  2  3
 4  5  6

In [59]:
arr2 = [1 2 3; 4 5 6]

2×3 Array{Int64,2}:
 1  2  3
 4  5  6

In [60]:
arr3 = [1, 2, 3]

3-element Array{Int64,1}:
 1
 2
 3

In [61]:
arr4 = [1; 2; 3]

3-element Array{Int64,1}:
 1
 2
 3

In [62]:
arr2 * arr2'

2×2 Array{Int64,2}:
 14  32
 32  77

In [63]:
arr2 .* arr2

2×3 Array{Int64,2}:
  1   4   9
 16  25  36

In [64]:
arr2 * arr4

2-element Array{Int64,1}:
 14
 32

In [65]:
arr2 .* [1; 2]

2×3 Array{Int64,2}:
 1   2   3
 8  10  12

### Álgebra lineal

In [66]:
using LinearAlgebra

#### Traspuesta

Como en otros lenguajes, `A'` es la transpuesta conjugada

In [67]:
arr2'

3×2 Adjoint{Int64,Array{Int64,2}}:
 1  4
 2  5
 3  6

In [68]:
arr_complex = rand(3, 3) + 1im * rand(3, 3)

3×3 Array{Complex{Float64},2}:
 0.686954+0.803361im   0.944847+0.335514im  0.0942912+0.0548651im
 0.628852+0.589378im  0.0363343+0.175687im   0.957406+0.63838im  
 0.847246+0.359153im   0.221742+0.266783im   0.787827+0.154139im 

In [69]:
arr_complex'

3×3 Adjoint{Complex{Float64},Array{Complex{Float64},2}}:
  0.686954-0.803361im    0.628852-0.589378im  0.847246-0.359153im
  0.944847-0.335514im   0.0363343-0.175687im  0.221742-0.266783im
 0.0942912-0.0548651im   0.957406-0.63838im   0.787827-0.154139im

In [70]:
transpose(arr_complex)

3×3 Transpose{Complex{Float64},Array{Complex{Float64},2}}:
  0.686954+0.803361im    0.628852+0.589378im  0.847246+0.359153im
  0.944847+0.335514im   0.0363343+0.175687im  0.221742+0.266783im
 0.0942912+0.0548651im   0.957406+0.63838im   0.787827+0.154139im

#### Inversa 

In [71]:
inv(arr)

3×3 Array{Float64,2}:
 -3.44735   -12.1863    8.97937
  0.143407    7.51496  -2.96594
  4.5228      9.88152  -7.93395

#### Sistemas lineales 

El problema $Ax=b$ para $A$ cuadrada se resulve con la función \.

In [72]:
A = [1 2; 3 4]
b = [10, 20]

x = A \ b

2-element Array{Float64,1}:
 0.0
 5.0

In [73]:
A * x 

2-element Array{Float64,1}:
 10.0
 20.0

También podríamos haber hecho:

In [74]:
inv(A) * b

2-element Array{Float64,1}:
 0.0
 5.0

Pero `\` es capaz de hacer muchas más cosas

In [75]:
?\

search: \



```
\(x, y)
```

Left division operator: multiplication of `y` by the inverse of `x` on the left. Gives floating-point results for integer arguments.

# Examples

```jldoctest
julia> 3 \ 6
2.0

julia> inv(3) * 6
2.0

julia> A = [4 3; 2 1]; x = [5, 6];

julia> A \ x
2-element Array{Float64,1}:
  6.5
 -7.0

julia> inv(A) * x
2-element Array{Float64,1}:
  6.5
 -7.0
```

---

```
\(A, B)
```

Matrix division using a polyalgorithm. For input matrices `A` and `B`, the result `X` is such that `A*X == B` when `A` is square. The solver that is used depends upon the structure of `A`.  If `A` is upper or lower triangular (or diagonal), no factorization of `A` is required and the system is solved with either forward or backward substitution. For non-triangular square matrices, an LU factorization is used.

For rectangular `A` the result is the minimum-norm least squares solution computed by a pivoted QR factorization of `A` and a rank estimate of `A` based on the R factor.

When `A` is sparse, a similar polyalgorithm is used. For indefinite matrices, the `LDLt` factorization does not use pivoting during the numerical factorization and therefore the procedure can fail even for invertible matrices.

# Examples

```jldoctest
julia> A = [1 0; 1 -2]; B = [32; -4];

julia> X = A \ B
2-element Array{Float64,1}:
 32.0
 18.0

julia> A * X == B
true
```

---

```
(\)(F::QRSparse, B::StridedVecOrMat)
```

Solve the least squares problem $\min\|Ax - b\|^2$ or the linear system of equations $Ax=b$ when `F` is the sparse QR factorization of $A$. A basic solution is returned when the problem is underdetermined.

# Examples

```jldoctest
julia> A = sparse([1,2,4], [1,1,1], [1.0,1.0,1.0], 4, 2)
4×2 SparseMatrixCSC{Float64,Int64} with 3 stored entries:
  [1, 1]  =  1.0
  [2, 1]  =  1.0
  [4, 1]  =  1.0

julia> qr(A)\fill(1.0, 4)
2-element Array{Float64,1}:
 1.0
 0.0
```


Cuando nuestra matriz es alta (número de renglones mayores al número de columnas), tenemos un sistema lineal sobredeterminado.


En este caso \ calcula la de mínimos cuadrados

In [76]:
A = [1 2; 3 4; 3.02 3.99]
b = [10, 20, 19.96]

A \ b

2-element Array{Float64,1}:
 0.005526745063674493
 4.997102719548115   

La función \ también sirve para problemas indeterminados. En este caso, la solución no es única y Julia regresa el valor con la menor norma.

#### Ejercicio 

In [ ]:
#preserve
B = reshape((2 .^ (1:1:36)), 6, 6) + rand(1:100, 6, 6)

Dada la matriz B, calcular:
- Su determinante para comprobar que no es singular
- Obtener su inversa
- Comprobar que $B B^{-1} = I$

In [ ]:
det(B)

In [ ]:
inv(B)

In [ ]:
inv(B) * B

In [ ]:
isapprox(one(B), inv(B) * B)

In [ ]:
isapprox.(one(B), inv(B)*B)

In [ ]:
cond(B)

In [ ]:
?cond

Una buena introducción al uso de arrays :

- https://en.wikibooks.org/wiki/Introducing_Julia/Arrays_and_tuples#Rows_and_Columns

## Más sobre arrays

En realidad los arrays en julia no tienen por qué ser de tipo homogéneo

In [ ]:
# Creamos un array con varios tipos
lista = ["25", 1, max]

In [ ]:
# no se puede insertar más allá del tamaño del array
lista[4] = [1, 2, 3]

In [ ]:
# para añadir elementos tenemos necesitamos
push!(lista, [1, 2, 3])

In [ ]:
# para quitarlos
pop!(lista)

In [ ]:
lista

In [ ]:
# para eliminar un índice en concreto
deleteat!(lista, 1)

In [ ]:
lista

En definitiva, los Arrays de Julia cumplen el papel que en Python tienen las listas y los arrays de NumPy

## Tuplas 

In [ ]:
tupla = (1, 2, 3)

In [ ]:
# son inmutables
tupla[1] = 5

In [ ]:
# son inmutables
pop!(tupla)

## Diccionarios 

In [ ]:
d = Dict("Julia" => ["dinámico", "JIT compilation"],
              "Fortran" => ["estático", "compilado"])

In [ ]:
d["Julia"]

In [ ]:
pop!(d, "Fortran")

In [ ]:
d["Python"] = ["dinámico", "interpretado"]

In [ ]:
d

In [ ]:
d["Matlab"] = "interpretado"

In [ ]:
d = Dict("Julia" => ["dinámico", "JIT compilation"],
              "Fortran" => ["estático", "compilado"],
              "Matlab" => "interpretado")

In [ ]:
customized_d = Dict{String, Union{String, Array{String, 1}}}()

In [ ]:
customized_d["a"] = "a" 

In [ ]:
customized_d["a"] = ["a"]

In [ ]:
customized_d["b"] = (1,)

In [ ]:
customized_d["c"] = [1 2 3; 4 5 6]

In [ ]:
for (key, val) in customized_d
    println(key, val)
end

## Condicionales y bucles 

In [ ]:
x = 5.1
y = 6.2;

In [ ]:
if x < y
    println("x es menor que y")
elseif x > y
    println("x es mayor que y")
else
    println("x es igual que y")
end

In [ ]:
x > y  ? "x es mayor que y" : "x es menor o igual que y"

In [ ]:
i = 1
while i < 1
    println("i vale: $(i)")
    i +=1
end

println("Fuera del while i vale: $(i)")

In [ ]:
for j = 1:10
           println("j vale: $(j)")
end

println("Fuera del while j vale: $(j)")

In [ ]:
j = 0

for j = 1:10
    println("j vale: $(j)")
end

println("Fuera del while j vale: $(j)")

In [ ]:
for j = 1:10
    local j
    j = 2j - j
    println("j vale: $(j)")
end

println("Fuera del while j vale: $(j)")

In [ ]:
for jj = 1:10
    global j=2jj-jj
    println("j vale: $(j)")
end

println("Fuera del while j vale: $(j)")

In [ ]:
# Bucle for condensado
for ii in 1:1:5, jj in 6:1:9
    println("ii, jj --> $(ii), $(jj)")
end

#### Ejercicio

Crea un diccionario `squares`, que tiene llaves de valores de 1 a 100. El valor asociado a cada llave es el cuadrado de la llave. Guarda los valores asociados a las llaves pares como enteros y las impares como cadenas. Por ejemplo,

```julia
squares[10] == 100
squares[11] == "121"
```

(¡No necesitas condicionales para esto!)

In [ ]:
squares = Dict{Int, Union{Int, String}}()

for ii in 1:2:99
    squares[ii] = ii^2
end

for ii in 2:2:100
    squares[ii] = string(ii^2)
end

squares

In [ ]:
sort(squares)

In [ ]:
using Pkg

Pkg.add("DataStructures")

In [ ]:
using DataStructures

In [ ]:
sort(squares)

In [ ]:
methods(sort)

---

In [1]:
using PyCall
display_ = pyimport("IPython.core.display")
css_file = "./style/style.css"
display_.HTML(pybuiltin("open")(css_file).read())

PyObject <IPython.core.display.HTML object>

┌ Warning: `getindex(o::PyObject, s::AbstractString)` is deprecated in favor of dot overloading (`getproperty`) so elements should now be accessed as e.g. `o."s"` instead of `o["s"]`.
│   caller = show(::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}, ::MIME{Symbol("text/html")}, ::PyObject) at PyCall.jl:895
└ @ PyCall /home/asaez/.julia/packages/PyCall/ttONZ/src/PyCall.jl:895
